apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-dev
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app-dev
  template:
    metadata:
      labels:
        app: flask-app-dev
    spec:
      containers:
      - name: flask-app
        image: ravindra806/my-python-app:dev
        ports:
        - containerPort: 5000