replicaCount: 1

image:
  repository: ravindra806/python-app
  tag: prod
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5000

containerPort: 5000

autoscaling:
  enabled: false

livenessProbe:
  httpGet:
    path: /
    port: 5000
  initialDelaySeconds: 10   # wait 10s before first probe
  periodSeconds: 10         # probe every 10s

readinessProbe:
  httpGet:
    path: /
    port: 5000
  initialDelaySeconds: 10
  periodSeconds: 10


resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

