apiVersion: v1
kind: Service
metadata:
  name: flask-service-prod
  namespace: prod
  labels:
    app: flask-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "classic"
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
    - name: http
      port: 80          # ELB listens here
      targetPort: 5000  # Flask app inside container
